import Head from 'next/head';
import { motion } from 'framer-motion';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">LovyD!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing <code>src/pages/index.js</code>
        </p>
        <div className={styles.grid}>
          <motion.a
            href="#"
            className={styles.card}
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
          >
            <h3>Documentation &rarr;</h3>
            <p>Find in-depth information about Next.js features and API.</p>
          </motion.a>
          <motion.a
            href="#"
            className={styles.card}
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
          >
            <h3>Learn &rarr;</h3>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </motion.a>
        </div>
      </main>
    </div>
  );
}
